# Generated by Django 3.1.4 on 2020-12-12 18:19

import carpool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoolRoom',
            fields=[
                ('room_id', models.CharField(default=carpool.models.get_code, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=120, unique=True)),
                ('details', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('members', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
