  
POST_REQUEST_ERRORS = {

    "INVALID_TOKEN": {
        "ERROR": "TOKEN_INVALID_OR_EXPIRED", 
        "MESSAGE": "PLEASE PROVIDE AUTH TOKEN IN POST HEADER. USE LOGIN API TO GET A TOKEN, OR TOKEN REFRESH IF TIMED OUT/EXPIRED"
        },
    "EXPIRED_TOKEN": {
        "ERROR": "TOKEN_EXPIRED", 
        "MESSAGE": "USE LOGIN API TO GET NEW TOKEN, OR TOKEN REFRESH IF TIMED OUT/EXPIRED"
        },
    "DATABASE_TIMED_OUT": {"ERROR": "DATABASE_DID_NOT_RESPOND"},
    "UNAUTHORISED": {"ERROR": "USER_UNAUTHORISED", "MESSAGE": "USER IS NOT ALLOWED TO MAKE THIS REQUEST. LOG IN AS ADMIN"}
}